### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by satohirok** [satohirok/protospace-37186#1]
# URL 

https://protospace-37186.herokuapp.com/

**Comment by miyu-yamamoto** [comment]
@satohirok さん、ご提出いただきありがとうございます。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **投稿ページで投稿に必要な情報が入力されていない場合は、投稿できずにそのページに留まるようにしましょう。**
空の項目がある状態で投稿しようとするとエラー画面が表示されます

- [ ] **ログイン・ログアウトの状態に関わらず、プロトタイプ一覧を閲覧できるようにしましょう。**
ログアウトの状態だと、トップページがログイン画面になっているため、プロトタイプ一覧を閲覧できません

- [ ] **プロトタイプ一覧ページにて、プロトタイプ毎に、画像・プロトタイプ名・キャッチコピー・投稿者の名前の、4つの情報について表示するようにしましょう。**
投稿者の名前が正しく表示されません。
 (以下に添付した画像の場合「qazx」というユーザーが投稿したものに対して「by25」と表示されております)
<img width="712" alt="スクリーンショット 2021-11-26 12 06 28" src="https://user-images.githubusercontent.com/59544869/143520736-7dcd8b19-cbb9-49f0-9fb4-a9747c465170.png">

- [ ] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像をクリックすると、該当する詳細ページへ遷移するようにしましょう。**
プロトタイプ詳細ページを開こうとするとエラー画面が表示されます

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう**
プロトタイプ一覧ページに表示される投稿者名をクリックしても、ユーザーの詳細ページへ遷移しません
(今回プロトタイプ詳細画面が開けなかったため、プロトタイプ詳細画面のプロトタイプ投稿者/コメント投稿者が正常にユーザー詳細ページに遷移するかは次回確認させていただきます)

- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されるようにしましょう。**
ユーザー名が正しく表示されない箇所があります
<img width="681" alt="スクリーンショット 2021-11-26 12 10 53" src="https://user-images.githubusercontent.com/59544869/143521102-ae99103a-9427-426c-8c8a-c68097999c33.png">


※ログアウト時の機能、編集機能、削除昨日、コメント機能等、確認できていない箇所は次回動作確認させていただきます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7
