### ISSUE TITLE
【依頼】ProtoSpace挙動確認#2

### ISSUE THREAD

**Issue by satohirok** [satohirok/protospace-37186#2]
#URL

https://protospace-37186b.herokuapp.com/

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移するようにしましょう**
①画像をクリックしたとき、以下のエラーページに遷移してしまいます。
②プロトタイプ名をクリックしたときに遷移しません。
<img width="655" alt="スクリーンショット 2021-11-29 12 49 13" src="https://user-images.githubusercontent.com/62644781/143806457-0ed245e1-0039-43dc-888a-56d5259ea1eb.png">


**※上記により、プロトタイプ詳細ページが確認できておりません。編集機能等は次回ご提出時に確認させていただきます。**

- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されるようにしましょう**
①登録した「所属」、「役職」が正しく表示されていません。
②そのユーザーが投稿したプロトタイプが表示されていません。
<img width="655" alt="スクリーンショット_2021-11-29_12_50_15" src="https://user-images.githubusercontent.com/62644781/143806390-ba51f80c-d9c8-4d53-9af6-390c6f35e454.png">

- [ ] **ログアウト状態のユーザーは、プロトタイプ新規投稿ページ・プロトタイプ編集ページに遷移しようとすると、ログインページにリダイレクトされるようにしましょう**
プロトタイプ新規投稿ページに遷移できてしまいます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by satohirok** [comment]
修正完了いたしましたので、修正したもの送らせていただきます。

**Comment by satohirok** [comment]
https://protospace-37186b.herokuapp.com/

挙動確認お願い致します。

**Comment by miyu-yamamoto** [comment]
@satohirok さん、お待たせいたしました。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **ログイン状態の投稿者だけが、自身の投稿したプロトタイプの詳細ページから削除ボタンをクリックすると、プロトタイプを削除できるようにしましょう。**
削除を押すとエラー画面になり、投稿を消すことができません

- [ ] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされるようにしましょう**
URLを直接入力することで、他のユーザーが投稿したプロトタイプの詳細ページを開くことができてしまいます

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by satohirok** [comment]
https://protospace-37186b.herokuapp.com/

修正いたしましたので、ご確認お願い致します。

**Comment by miyu-yamamoto** [comment]
ご提出いただきありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
